services:
  arr-fileflows:
    image: revenz/fileflows:latest
    container_name: arr-fileflows
    restart: "no"
    ports:
      - "19200:5000"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "${RENDER_GID}"
      - "${VIDEO_GID}"
    volumes:
      - ./config:/app/Data
      - ./temp:/temp
      - ${MEDIA_PATH}:/media
    deploy:
      resources:
        limits:
          memory: 3g
        reservations:
          memory: 1g
