services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: always
    ports:
      - "8096:8096"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./jellyconfig:/config
      - ./jellycache:/cache
      - ${MEDIA_PATH}:/media
    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        limits:
          memory: 3g
        reservations:
          memory: 1g

  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    container_name: seerr
    restart: "no"
    init: true
    environment:
      - TZ=${TZ}
      - LOG_LEVEL=info
    ports:
      - "5055:5055"
    volumes:
      - ./seerrconfig:/app/config
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 384m
