services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: always
    network_mode: host
    volumes:
      - ./adguard-work:/opt/adguardhome/work
      - ./adguard-conf:/opt/adguardhome/conf
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
