---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/
layout:
  Infrastructure:
    style: row
    columns: 3

  Monitoring:
    style: row
    columns: 3

  Media:
    style: row
    columns: 3

  ARR-Stack:
    style: row
    columns: 4

  Development:
    style: row
    columns: 3

  Gaming:
    style: row
    columns: 3