services:
  openvscode-server:
    build:
      context: .
      dockerfile: Dockerfile.openvscode
    image: local/openvscode-server:ssh
    container_name: openvscode-server
    restart: unless-stopped
    init: true
    ports:
      - "3050:3000"
    environment:
      TZ: ${TZ}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${DIR}:${DIR}
      - ${NAS}:${NAS}
      - ./openvscode-ssh:/home/openvscode-server/.ssh
      - ./openvscode-data:/home/openvscode-server/data
      - ./workspace:/home/openvscode-server/workspace
    entrypoint:
      - /home/.openvscode-server/bin/openvscode-server
    command:
      - --host
      - 0.0.0.0
      - --connection-token
      - ${OPENVSCODE_TOKEN}
      - --user-data-dir
      - /home/openvscode-server/data/user-data
      - --extensions-dir
      - /home/openvscode-server/data/extensions
      - ${OPENVSCODE_WORKSPACE}
