services:
  valheim-server:
    image: lloesche/valheim-server:latest
    container_name: valheim-server
    restart: "no"
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
    environment:
      - SERVER_NAME=${VALHEIM_SERVER_NAME}
      - WORLD_NAME=${VALHEIM_WORLD_NAME}
      - SERVER_PASS=${VALHEIM_SERVER_PASS}
      - SERVER_PUBLIC=${VALHEIM_SERVER_PUBLIC}
      - SERVER_ARGS=${VALHEIM_SERVER_ARGS}
      - BEPINEX=${VALHEIM_BEPINEX}
    volumes:
      - ./valheim_config:/config
    deploy:
      resources:
        limits:
          memory: 10g
        reservations:
          memory: 5g
