services:
  pgadmin:
    image: dpage/pgadmin4:9.16
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_DISABLE_POSTFIX: "true"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "127.0.0.1:5050:80"
    networks:
      - database-admin-network

volumes:
  pgadmin-data:
    name: database-admin-pgadmin-data

networks:
  database-admin-network:
    external: true
    name: database-admin-network
